// Ephemeral test-profile factory.
//
// Creates a fresh Firefox profile directory under the OS temp dir, populated
// with palefox's chrome/ contents and a user.js that enables Marionette and
// disables anything that would slow down or interrupt headless tests.
//
// Caller pattern:
//   const profile = await createProfile();
//   try { /* spawn firefox -profile profile.path ... */ }
//   finally { await profile.cleanup(); }

import { mkdtemp, mkdir, writeFile, rm, copyFile, readdir, stat } from "node:fs/promises";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";

export interface TestProfile {
  /** Absolute path to the ephemeral profile directory. */
  path: string;
  /** Removes the profile directory. Call from a finally block. */
  cleanup(): Promise<void>;
}

/** Recursively copy `from` → `to`. We avoid symlinks because Firefox's autoconfig
 *  loader is finicky about chrome.manifest path resolution and we want the test
 *  to mirror real install behavior. */
async function copyDir(from: string, to: string): Promise<void> {
  await mkdir(to, { recursive: true });
  for (const entry of await readdir(from)) {
    const src = join(from, entry);
    const dst = join(to, entry);
    const s = await stat(src);
    if (s.isDirectory()) {
      await copyDir(src, dst);
    } else if (s.isFile()) {
      await copyFile(src, dst);
    }
  }
}

/** Default user.js — enables Marionette + sane test prefs. The `pfx.debug`
 *  pref defaults true so tests have access to file-based logs if a failure
 *  needs deeper inspection. */
const DEFAULT_USER_JS = `// Generated by tools/test-driver — DO NOT EDIT.
// Marionette
user_pref("marionette.port", 2828);
user_pref("marionette.enabled", true);
// Disable update / upgrade flows that can interrupt headless tests
user_pref("app.update.enabled", false);
user_pref("app.update.auto", false);
user_pref("app.update.silent", false);
user_pref("app.update.checkInstallTime", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
// No first-run / what's-new flows
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("startup.homepage_welcome_url", "");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("startup.homepage_override_url", "");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
// Restore previous session on startup — needed for tree-reconciliation
// tests that kill Firefox and expect tabs to come back.
//   browser.startup.page = 3 → "Restore previous session"
user_pref("browser.startup.page", 3);
user_pref("browser.sessionstore.resume_from_crash", true);
user_pref("toolkit.startup.max_resumed_crashes", -1);
// Vertical tabs (palefox default-on territory)
user_pref("sidebar.verticalTabs", true);
user_pref("sidebar.revamp", true);
// Palefox debug logging on so failed runs leave a trail
user_pref("pfx.debug", true);
// Expose window.pfxTest for direct internal-state access in tests. Only
// active when this pref is set; production builds never expose it.
user_pref("pfx.test.exposeAPI", true);
// Skip the legacy compatibility shield warning
user_pref("xpinstall.signatures.required", false);
// Disable telemetry / data submission for clean profiles
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
`;

/** Create an ephemeral test profile.
 *
 * @param chromeSource  Path to the palefox `chrome/` directory (defaults to
 *                      <repo>/chrome relative to where this is invoked).
 * @param extraPrefs    Optional extra user_pref lines to append to user.js.
 */
export async function createProfile(opts: {
  chromeSource?: string;
  extraPrefs?: string;
} = {}): Promise<TestProfile> {
  const chromeSource = opts.chromeSource
    ?? join(process.cwd(), "chrome");
  // Sanity check — we want the user to fail fast if chrome/ isn't where we
  // expect, rather than spawning Firefox with an empty profile.
  try {
    await stat(chromeSource);
  } catch {
    throw new Error(
      `tools/test-driver: chrome source not found at ${chromeSource}.\n` +
      `Did you run \`bun run build\`?`,
    );
  }

  const path = await mkdtemp(join(tmpdir(), "palefox-test-"));
  // Profile structure: <profile>/chrome/, <profile>/user.js
  await copyDir(chromeSource, join(path, "chrome"));
  const userJs = DEFAULT_USER_JS + (opts.extraPrefs ?? "");
  await writeFile(join(path, "user.js"), userJs, "utf8");

  return {
    path,
    async cleanup() {
      await rm(path, { recursive: true, force: true });
    },
  };
}
